language: ruby
env:
    - RAILS_ENV=test
gemfile: 
    - Gemfile
before_install:
    - gem update --system
    - gem install bundler
    # Yarn (JS assets) - https://yarnpkg.com/en/docs/install-ci#travis-tab
    - yarn install
cache:
    yarn: true
script: 
    - bundle exec rubocop -D
    - bundle exec rails test